/* ============================================================================
 * eventviewer.js — Event Viewer (Windows 98 System Tools)
 *
 * This is deliberately a polling viewer.  The kernel already exposes useful
 * counters and text logs, and polling keeps the viewer read-only while still
 * showing activity generated by the other applications.  A small, bounded
 * buffer prevents a busy guest or timer queue from growing the DOM forever.
 * ========================================================================== */
(function (global) {
  'use strict';

  var W98 = global.W98;
  if (!W98 || typeof W98.registerApp !== 'function') return;

  var ID = 'eventviewer';
  var MAX_EVENTS = 500;
  var CHANNELS = ['Application', 'System', 'Kernel', 'Hyper-V'];
  var TYPES = ['Information', 'Warning', 'Error'];
  var PROC_STATES = { 0: 'Empty', 1: 'Running', 2: 'Minimized', 3: 'Hidden', 4: 'Zombie' };
  var U = W98.util || {};

  function makeEl(tag, cls, value) {
    var e = U.el ? U.el(tag, cls) : document.createElement(tag);
    if (value != null) e.textContent = String(value);
    return e;
  }
  function safe(fn, fallback) {
    try {
      var v = fn();
      return v === undefined ? fallback : v;
    } catch (e) { return fallback; }
  }
  function text(v, fallback) {
    if (v == null) return fallback == null ? '' : String(fallback);
    return String(v);
  }
  function number(v) {
    return typeof v === 'number' && isFinite(v) ? v : null;
  }
  function counter(st, upper, lower) {
    if (!st || typeof st !== 'object') return null;
    var v = st[upper];
    if (v === undefined && lower) v = st[lower];
    return number(v);
  }
  function delta(now, before) {
    var n = number(now), p = number(before);
    return n == null || p == null ? null : n - p;
  }
  function processState(p) {
    if (!p) return 'Unknown';
    return text(p.stateName, PROC_STATES[p.state] || p.state || 'Unknown');
  }
  function nowStamp() {
    var n = Date.now();
    try {
      if (W98.fs && typeof W98.fs.timeString === 'function') {
        var up = typeof W98.tick === 'function' ? W98.tick() : 0;
        return W98.fs.timeString(up);
      }
    } catch (e) { /* fall back to the browser clock */ }
    var d = new Date(n);
    function p(v) { return v < 10 ? '0' + v : String(v); }
    return p(d.getMonth() + 1) + '/' + p(d.getDate()) + '/' + d.getFullYear() + ' ' +
      p(d.getHours()) + ':' + p(d.getMinutes()) + ':' + p(d.getSeconds());
  }
  function timestamp() {
    var n = Date.now();
    try {
      if (W98.fs && typeof W98.fs.timeString === 'function') {
        var up = typeof W98.tick === 'function' ? W98.tick() : 0;
        /* fs.timeString returns a Win98 formatted timestamp. */
        return { text: W98.fs.timeString(up), value: n };
      }
    } catch (e) { /* use Date below */ }
    return { text: nowStamp(), value: n };
  }

  function sourceLog() {
    var value = null;
    if (typeof W98.logText === 'function') value = safe(function () { return W98.logText(); }, null);
    if (value == null && typeof W98.kernelLog === 'function') value = safe(function () { return W98.kernelLog(); }, null);
    if (value == null && W98.kernel && typeof W98.kernel.logText === 'function') {
      value = safe(function () { return W98.kernel.logText(); }, null);
    }
    return typeof value === 'string' ? value : '';
  }
  /* A short, read-only registry snapshot makes a counter change useful to a
     person reading the log.  Enumeration is capped so a large hive cannot
     stall the polling timer. */
  function registryDetails() {
    if (typeof W98.regEnum !== 'function') return '';
    var count = typeof W98.regCount === 'function' ? number(safe(function () { return W98.regCount(); }, 0)) : 8;
    count = Math.max(0, Math.min(count == null ? 8 : count, 8));
    var out = [];
    for (var i = 0; i < count; i++) {
      var r = safe(function (index) { return function () { return W98.regEnum(index); }; }(i), null);
      if (r) out.push(text(r.path, '') + '\\' + text(r.name, '') + '=' + text(r.value, ''));
    }
    return out.join('; ');
  }

  function classifyLog(line) {
    var s = String(line || '').toLowerCase();
    var channel = 'Kernel', source = 'Kernel log', type = 'Information', id = 1100;
    if (/hyper.?v|hypercall|hv_|partition|slat/.test(s)) {
      channel = 'Hyper-V'; source = 'Hyper-V log'; id = 4100;
    } else if (/vmbus|channel|guest|heartbeat|synic/.test(s)) {
      channel = 'Hyper-V'; source = 'VMBus'; id = 4200;
    } else if (/registry|hive|reg(ed|istry)?[ :]/.test(s)) {
      channel = 'System'; source = 'Registry'; id = 3001;
    } else if (/file system|filesystem|\bfs\b|file[ :]/.test(s)) {
      channel = 'System'; source = 'File System'; id = 3000;
    } else if (/bugcheck|panic|halt|fatal|exception|error/.test(s)) {
      channel = 'System'; source = 'Kernel'; type = 'Error'; id = 4000;
    } else if (/warn|degrad|drop/.test(s)) {
      type = 'Warning'; id = 1101;
    } else if (/application|window|shell/.test(s)) {
      channel = 'Application'; source = 'Windows shell'; id = 1000;
    }
    return { channel: channel, source: source, type: type, id: id };
  }

  function hvSurface() {
    var h = null;
    try { h = global.W98HV || (W98 && W98.hv) || null; } catch (e) { h = null; }
    return h;
  }
  function hvNumber(h, name) {
    if (!h || typeof h[name] !== 'function') return null;
    return number(safe(function () { return h[name](); }, null));
  }
  function hvLogText(h) {
    if (!h) return '';
    var fn = typeof h.log === 'function' ? h.log : (typeof h.hypervisorLog === 'function' ? h.hypervisorLog : null);
    return fn ? text(safe(function () { return fn.call(h); }, ''), '') : '';
  }
  function hvSnapshot() {
    var h = hvSurface();
    if (!h) return null;
    var out = { mode: h.mode || '', hypercalls: null, vmbus: null, heartbeat: {} };
    var st = null;
    if (typeof h.stats === 'function') st = safe(function () { return h.stats(); }, null);
    if (st && typeof st === 'object') {
      out.mode = st.mode || out.mode;
      out.hypercalls = number(st.hypercalls);
      var vb = {
        messages: number(st.channelMessages != null ? st.channelMessages : st.vmbusMessages),
        dropped: number(st.channelDropped),
        inBytes: number(st.channelIn != null ? st.channelIn : st.vmbusInBytes),
        outBytes: number(st.channelOut != null ? st.channelOut : st.vmbusOutBytes)
      };
      if (out.mode !== 'none' || vb.messages != null || vb.dropped != null || vb.inBytes != null || vb.outBytes != null) out.vmbus = vb;
    }
    if (out.hypercalls == null) out.hypercalls = hvNumber(h, 'hypercalls');
    if (!out.vmbus && out.mode !== 'none' && typeof h.vmbusStats === 'function') {
      var vs = safe(function () { return h.vmbusStats(); }, null);
      if (vs && typeof vs === 'object') out.vmbus = {
        messages: number(vs.messages), dropped: number(vs.dropped),
        inBytes: number(vs.inBytes), outBytes: number(vs.outBytes)
      };
    }
    if (!out.vmbus && out.mode !== 'none' && typeof h.vmbus === 'function') {
      var chans = safe(function () { return h.vmbus(); }, []);
      if (chans && chans.channels) chans = chans.channels;
      if (Array.isArray(chans)) {
        out.vmbus = { messages: null, dropped: null, inBytes: null, outBytes: null };
        function addVmbus(field, value) {
          value = number(value);
          if (value == null) return;
          out.vmbus[field] = out.vmbus[field] == null ? value : out.vmbus[field] + value;
        }
        chans.forEach(function (c) {
          addVmbus('messages', c.messages);
          addVmbus('dropped', c.dropped);
          addVmbus('inBytes', c.inBytes);
          addVmbus('outBytes', c.outBytes);
        });
      }
    }
    /* The kernel transport has a compact numeric counter API.  Prefer it when
       the optional hypervisor is absent; the two counters describe the same
       guest transport at different layers and should not be added together. */
    if ((!out.mode || out.mode === 'none') && typeof W98.vmbusStats === 'function') {
      var topVmbus = safe(function () { return W98.vmbusStats(); }, null);
      if (topVmbus && typeof topVmbus === 'object') out.vmbus = {
        messages: number(topVmbus.messages), inBytes: number(topVmbus.inBytes),
        dropped: number(topVmbus.dropped), outBytes: number(topVmbus.outBytes)
      };
      else if (number(topVmbus) != null) out.vmbus = { messages: number(topVmbus), inBytes: null, dropped: null, outBytes: null };
    }
    if ((!out.mode || out.mode === 'none') && !out.vmbus && W98.kernel && typeof W98.kernel.vmbusStats === 'function') {
      out.vmbus = {
        messages: number(safe(function () { return W98.kernel.vmbusStats(0); }, null)),
        inBytes: number(safe(function () { return W98.kernel.vmbusStats(1); }, null)),
        dropped: null, outBytes: null
      };
    }
    var parts = null;
    if (typeof h.partitions === 'function') parts = safe(function () { return h.partitions(); }, []);
    if (!Array.isArray(parts) && typeof h.partitionList === 'function') parts = safe(function () { return h.partitionList(); }, []);
    if (Array.isArray(parts)) parts.forEach(function (part) {
      var id = part && (part.id != null ? part.id : part.partition);
      /* Partition IDs are opaque values.  If a fixture cannot provide one,
         leave its guest heartbeat unavailable instead of guessing a slot. */
      if (id == null) return;
      var g = null;
      if (typeof h.guestFields === 'function') g = safe(function () { return h.guestFields(id); }, null);
      if (!g && typeof h.guest === 'function') g = safe(function () { return h.guest(id); }, null);
      if (g && number(g.heartbeat) != null) out.heartbeat[id] = number(g.heartbeat);
    });
    return out;
  }

  W98.registerApp({
    id: ID,
    title: 'Event Viewer',
    icon: 'system',
    width: 700,
    height: 420,
    minWidth: 540,
    minHeight: 280,
    resizable: true,
    maximizable: true,
    singleton: true,
    startMenuGroup: 'System Tools',
    create: create
  });

  function create(win) {
    var state = {
      events: [],
      selected: null,
      channel: '',
      type: '',
      source: '',
      search: '',
      previous: null,
      previousLog: null,
      previousHvLog: null,
      previousHv: null,
      procMap: null,
      timer: null,
      timerIsRaf: false
    };

    ensureCss();
    win.el.style.display = 'flex';
    win.el.style.flexDirection = 'column';
    win.el.style.overflow = 'hidden';

    var root = makeEl('div', 'ev-root');
    var toolbar = makeEl('div', 'ev-toolbar');
    var refresh = makeEl('button', '', 'Refresh');
    var clear = makeEl('button', '', 'Clear View');
    var save = makeEl('button', '', 'Save View');
    [refresh, clear, save].forEach(function (b) { b.style.minWidth = '76px'; toolbar.appendChild(b); });
    toolbar.appendChild(makeEl('span', 'ev-sep', '|'));
    toolbar.appendChild(makeEl('span', '', 'Channel:'));
    var channel = makeEl('select');
    addOption(channel, '', 'All'); CHANNELS.forEach(function (c) { addOption(channel, c, c); });
    toolbar.appendChild(channel);
    toolbar.appendChild(makeEl('span', '', 'Type:'));
    var type = makeEl('select');
    addOption(type, '', 'All'); TYPES.forEach(function (t) { addOption(type, t, t); });
    toolbar.appendChild(type);
    toolbar.appendChild(makeEl('span', '', 'Source:'));
    var source = makeEl('input'); source.type = 'text'; source.size = 12; source.maxLength = 80;
    toolbar.appendChild(source);
    toolbar.appendChild(makeEl('span', '', 'Text:'));
    var search = makeEl('input'); search.type = 'text'; search.size = 16; search.maxLength = 120;
    toolbar.appendChild(search);
    root.appendChild(toolbar);

    var list = makeEl('div', 'ev-list');
    var table = makeEl('table', 'ev-table');
    var head = makeEl('thead');
    var hr = makeEl('tr');
    [['Timestamp', 'ev-time'], ['Source', 'ev-source'], ['Event ID', 'ev-id'], ['Type', 'ev-type'], ['Message', 'ev-message']].forEach(function (c) {
      var th = makeEl('th', c[1], c[0]); hr.appendChild(th);
    });
    head.appendChild(hr); table.appendChild(head);
    var body = makeEl('tbody'); table.appendChild(body); list.appendChild(table); root.appendChild(list);
    var status = makeEl('div', 'ev-status', 'No events recorded.'); root.appendChild(status);
    win.el.appendChild(root);

    function updateStatus() {
      var shown = filtered().length;
      status.textContent = shown + ' event' + (shown === 1 ? '' : 's') + ' shown (' + state.events.length + ' stored; maximum ' + MAX_EVENTS + ').';
      if (!state.events.length) status.textContent = 'No events recorded. Signals will appear when the kernel or hypervisor reports activity.';
      var hv = hvSurface();
      if (!hv || hv.mode === 'none') status.textContent += ' Hyper-V is unavailable.';
    }
    function filtered() {
      var c = state.channel.toLowerCase(), t = state.type.toLowerCase(), s = state.source.toLowerCase(), q = state.search.toLowerCase();
      return state.events.filter(function (e) {
        var all = (e.channel + ' ' + e.source + ' ' + e.id + ' ' + e.type + ' ' + e.message).toLowerCase();
        return (!c || e.channel.toLowerCase() === c) && (!t || e.type.toLowerCase() === t) &&
          (!s || e.source.toLowerCase().indexOf(s) >= 0) && (!q || all.indexOf(q) >= 0);
      });
    }
    function render() {
      while (body.firstChild) body.removeChild(body.firstChild);
      var listEvents = filtered();
      if (!listEvents.length) {
        var row = makeEl('tr', 'ev-empty');
        var cell = makeEl('td', '', state.events.length ? 'No events match the current filters.' : 'No events recorded. Signals will appear when the kernel or hypervisor reports activity.');
        cell.colSpan = 5; row.appendChild(cell); body.appendChild(row);
      } else listEvents.forEach(function (event) {
        var row = makeEl('tr', 'ev-row');
        if (state.selected === event) row.className += ' selected';
        [event.timestamp, event.source, event.id, event.type, event.message].forEach(function (v, i) {
          var cell = makeEl('td', i === 4 ? 'ev-message' : '', v); row.appendChild(cell);
        });
        row.onclick = function () { state.selected = event; render(); };
        row.ondblclick = function () { showDetails(event); };
        row.onkeydown = function (ev) { if (ev.key === 'Enter') showDetails(event); };
        row.tabIndex = 0;
        body.appendChild(row);
      });
      updateStatus();
    }
    function pushEvent(channelName, sourceName, id, eventType, message, details) {
      var stamp = timestamp();
      state.events.push({ timestamp: stamp.text, time: stamp.value, channel: channelName, source: sourceName,
        id: id, type: eventType, message: String(message), details: details || String(message) });
      if (state.events.length > MAX_EVENTS) state.events.splice(0, state.events.length - MAX_EVENTS);
    }
    function showDetails(event) {
      var details = 'Timestamp:\t' + event.timestamp + '\n' +
        'Channel:\t' + event.channel + '\n' + 'Source:\t' + event.source + '\n' +
        'Event ID:\t' + event.id + '\n' + 'Type:\t' + event.type + '\n\n' + event.message +
        (event.details && event.details !== event.message ? '\n\nDetails:\n' + event.details : '');
      if (W98.dialog && typeof W98.dialog.alert === 'function') {
        safe(function () { W98.dialog.alert('Event Details', details, event.type === 'Error' ? 'error' : event.type === 'Warning' ? 'warn' : 'info'); }, null);
      } else if (typeof global.alert === 'function') global.alert(details);
    }
    function saveView() {
      var lines = ['Windows 98 Event Viewer', 'Saved: ' + nowStamp(), ''];
      lines.push('Timestamp\tChannel\tSource\tEvent ID\tType\tMessage');
      filtered().forEach(function (e) { lines.push([e.timestamp, e.channel, e.source, e.id, e.type, e.message].join('\t')); });
      var out = lines.join('\n');
      try {
        if (typeof Blob === 'function' && global.URL && typeof global.URL.createObjectURL === 'function') {
          var url = global.URL.createObjectURL(new Blob([out], { type: 'text/plain' }));
          var a = makeEl('a'); a.href = url; a.download = 'event-viewer.txt';
          (document.body || root).appendChild(a); a.click(); if (a.parentNode) a.parentNode.removeChild(a);
          setTimeout(function () { try { global.URL.revokeObjectURL(url); } catch (e) {} }, 0);
        }
      } catch (e) { /* saving is a convenience; it must never affect the viewer */ }
      if (!out) return;
    }
    function readProcesses() {
      var p = typeof W98.kernelProcs === 'function' ? safe(function () { return W98.kernelProcs(); }, []) : [];
      return Array.isArray(p) ? p : [];
    }
    function poll() {
      var st = typeof W98.stats === 'function' ? safe(function () { return W98.stats(); }, {}) : {};
      if (!st || typeof st !== 'object') st = {};
      var procs = readProcesses(), currentMap = {};
      procs.forEach(function (p) { if (p && p.pid != null) currentMap[p.pid] = p; });
      if (state.procMap) {
        Object.keys(currentMap).forEach(function (pid) {
          if (!state.procMap[pid]) pushEvent('Kernel', 'Process Manager', 1000, 'Information',
            'Process started: ' + text(currentMap[pid].name, 'pid ' + pid) + ' (PID ' + pid + ').');
          else if (currentMap[pid].state !== state.procMap[pid].state) pushEvent('Kernel', 'Process Manager', 1002, 'Information',
            'Process state changed: ' + text(currentMap[pid].name, 'PID ' + pid) + ' (PID ' + pid + ') is now ' + processState(currentMap[pid]) + '.');
        });
        Object.keys(state.procMap).forEach(function (pid) {
          if (!currentMap[pid]) pushEvent('Kernel', 'Process Manager', 1001, 'Information',
            'Process exited: PID ' + pid + ' (' + text(state.procMap[pid].name, 'unknown') + ').');
        });
      }
      state.procMap = currentMap;
      if (state.previous) {
        var d = delta(counter(st, 'FIRED', 'timersFired'), counter(state.previous, 'FIRED', 'timersFired'));
        if (d != null && d > 0) pushEvent('Kernel', 'Timer Manager', 2000, 'Information', d + ' kernel timer' + (d === 1 ? '' : 's') + ' fired.');
        d = delta(counter(st, 'QUEUE', 'timerQueue'), counter(state.previous, 'QUEUE', 'timerQueue'));
        if (d != null && d !== 0) pushEvent('Kernel', 'Timer Manager', 2001, 'Information', 'Timer queue depth changed to ' + text(counter(st, 'QUEUE', 'timerQueue'), '?') + '.');
        var fd = delta(counter(st, 'FILES', 'files'), counter(state.previous, 'FILES', 'files'));
        var bd = delta(counter(st, 'BYTES', 'bytes'), counter(state.previous, 'BYTES', 'bytes'));
        if ((fd != null && fd !== 0) || (bd != null && bd !== 0)) {
          pushEvent('System', 'File System', 3000, 'Information', 'File system counters changed: ' + text(counter(st, 'FILES', 'files'), '?') + ' files, ' + text(counter(st, 'BYTES', 'bytes'), '?') + ' bytes.');
        }
        var rd = delta(counter(st, 'REG', 'registry'), counter(state.previous, 'REG', 'registry'));
        if (rd != null && rd !== 0) {
          var regText = registryDetails();
          pushEvent('System', 'Registry', 3001, 'Information', 'Registry activity detected (' + text(counter(st, 'REG', 'registry'), '?') + ' values).', regText);
        }
        var ex = W98.kernel && typeof W98.kernel.exec === 'function' ? safe(function () { return W98.kernel.exec(); }, null) : null;
        if (ex && state.previous.exec && delta(ex.bugchecks, state.previous.exec.bugchecks) > 0) {
          var dump = typeof ex.bugcheckDump === 'function' ? safe(function () { return ex.bugcheckDump(); }, '') : '';
          pushEvent('System', 'BugCheck', 4000, 'Error', 'Kernel bugcheck detected (' + text(ex.bugchecks, '?') + ').', dump);
        }
        state.previous.exec = ex;
      } else {
        state.previous = {};
        state.previous.exec = W98.kernel && typeof W98.kernel.exec === 'function' ? safe(function () { return W98.kernel.exec(); }, null) : null;
      }
      state.previous = Object.assign({}, st, { exec: state.previous.exec });

      var log = sourceLog();
      if (state.previousLog === null) {
        state.previousLog = log;
        if (log) log.split(/\r?\n/).filter(Boolean).slice(-50).forEach(addLogEvent);
      } else if (log && log !== state.previousLog) {
        var suffix = log.indexOf(state.previousLog) === 0 ? log.slice(state.previousLog.length) : log;
        suffix.split(/\r?\n/).filter(Boolean).slice(-100).forEach(addLogEvent);
        state.previousLog = log;
      }
      var hv = hvSnapshot();
      if (hv) {
        if (state.previousHv) {
          var hd = delta(hv.hypercalls, state.previousHv.hypercalls);
          if (hd != null && hd > 0) pushEvent('Hyper-V', 'Hypercall Interface', 4100, 'Information', hd + ' hypercall' + (hd === 1 ? '' : 's') + ' completed.');
          if (hv.vmbus && state.previousHv.vmbus) {
            var vd = delta(hv.vmbus.messages, state.previousHv.vmbus.messages);
            if (vd != null && vd > 0) pushEvent('Hyper-V', 'VMBus', 4200, 'Information', vd + ' VMBus message' + (vd === 1 ? '' : 's') + ' transferred.');
            vd = delta(hv.vmbus.dropped, state.previousHv.vmbus.dropped);
            if (vd != null && vd > 0) pushEvent('Hyper-V', 'VMBus', 4201, 'Warning', vd + ' VMBus message' + (vd === 1 ? '' : 's') + ' dropped.');
          }
          Object.keys(hv.heartbeat).forEach(function (id) {
            var old = state.previousHv.heartbeat[id], n = hv.heartbeat[id];
            if (number(old) != null && n !== old) pushEvent('Hyper-V', 'Guest heartbeat', 4300, 'Information', 'Guest partition ' + id + ' heartbeat changed from ' + old + ' to ' + n + '.');
          });
        }
        state.previousHv = hv;
        var hlog = hvLogText(hvSurface());
        if (state.previousHvLog === null) {
          state.previousHvLog = hlog;
          if (hlog) hlog.split(/\r?\n/).filter(Boolean).slice(-30).forEach(addHvLogEvent);
        } else if (hlog && hlog !== state.previousHvLog) {
          var htail = hlog.indexOf(state.previousHvLog) === 0 ? hlog.slice(state.previousHvLog.length) : hlog;
          htail.split(/\r?\n/).filter(Boolean).slice(-50).forEach(addHvLogEvent);
          state.previousHvLog = hlog;
        }
      }
      render();
    }
    function addLogEvent(line) {
      var c = classifyLog(line);
      pushEvent(c.channel, c.source, c.id, c.type, String(line));
    }
    function addHvLogEvent(line) {
      var c = classifyLog(line);
      pushEvent('Hyper-V', 'Hyper-V log', 4101, c.type, String(line));
    }

    refresh.onclick = function () { poll(); };
    clear.onclick = function () { state.events = []; state.selected = null; render(); };
    save.onclick = function () { saveView(); };
    channel.onchange = function () { state.channel = channel.value; render(); };
    type.onchange = function () { state.type = type.value; render(); };
    source.oninput = source.onchange = function () { state.source = source.value; render(); };
    search.oninput = search.onchange = function () { state.search = search.value; render(); };
    render();
    poll();
    if (typeof win.setInterval === 'function') state.timer = win.setInterval(poll, 1000);
    else if (typeof W98.raf === 'function') {
      var elapsed = 0;
      state.timerIsRaf = true;
      state.timer = W98.raf(function (dt) {
        elapsed += number(dt) || 16;
        if (elapsed >= 1000) { elapsed = 0; poll(); }
      });
    }
    if (typeof win.on === 'function') win.on('close', function () {
      if (!state.timer) return;
      try {
        if (state.timerIsRaf && typeof state.timer === 'function') state.timer();
        else if (typeof win.clearInterval === 'function') win.clearInterval(state.timer);
      } catch (e) { /* Window.close also clears kernel timers. */ }
      state.timer = null;
    });
  }

  function addOption(select, value, label) {
    var option = makeEl('option', '', label); option.value = value; select.appendChild(option);
  }
  function ensureCss() {
    if (document.getElementById('w98app-' + ID)) return;
    var st = document.createElement('style'); st.id = 'w98app-' + ID;
    st.textContent =
      '.ev-root{display:flex;flex-direction:column;width:100%;height:100%;min-height:0;background:#c0c0c0;font:11px Tahoma,"MS Sans Serif",sans-serif;color:#000}' +
      '.ev-root *{box-sizing:border-box}.ev-toolbar{display:flex;align-items:center;gap:4px;min-height:30px;padding:4px;flex:0 0 auto;white-space:nowrap;overflow:hidden}' +
      '.ev-toolbar select{height:20px;min-width:70px}.ev-toolbar input{height:20px;min-width:52px}.ev-sep{color:#808080;padding:0 2px}' +
      '.ev-list{flex:1 1 auto;min-height:60px;overflow:auto;margin:0 4px;background:#fff;border:1px solid #808080;box-shadow:inset 1px 1px #000,inset -1px -1px #fff}' +
      '.ev-table{border-collapse:collapse;width:100%;table-layout:fixed;font:11px Tahoma,"MS Sans Serif",sans-serif}' +
      '.ev-table th{position:sticky;top:0;background:#c0c0c0;text-align:left;font-weight:normal;padding:2px 4px;height:20px;border-right:1px solid #808080;border-bottom:1px solid #808080;box-shadow:inset 1px 1px #fff}' +
      '.ev-table td{padding:2px 4px;height:19px;border-bottom:1px solid #dfdfdf;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}' +
      '.ev-time{width:142px}.ev-source{width:122px}.ev-id{width:58px}.ev-type{width:78px}.ev-message{width:auto}' +
      '.ev-row{cursor:default}.ev-row:hover{background:#dfe8f5}.ev-row.selected{background:#000080;color:#fff}.ev-empty td{text-align:center;color:#808080;padding:18px;white-space:normal}' +
      '.ev-status{flex:0 0 21px;padding:3px 6px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;border-top:1px solid #808080;background:#c0c0c0}';
    (document.head || document.documentElement).appendChild(st);
  }
})(typeof window !== 'undefined' ? window : this);
